### ISSUE TITLE
e2e tests give errors when run locally.

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#402]
## Describe the bug

When running the e2e tests locally, per the [instructions](https://github.com/Parsely/wp-parsely/blob/develop/tests/e2e/README.md), then I get a constant error for each of them. When the tests are run in the CI, then it passes correctly ([example](https://github.com/Parsely/wp-parsely/runs/3708536507?check_suite_focus=true)).

## To Reproduce
```
$ npm run test:e2e

> test:e2e
> wp-scripts test-e2e

Chromium is already in /Users/gary/Sites/wp-parsely/app/public/wp-content/plugins/wp-parsely/node_modules/puppeteer-core/.local-chromium/mac-901912; skipping download.
 FAIL  tests/e2e/specs/plugin-action-link.spec.js
  ● Plugin action link › Should link to plugin settings page

    thrown: Response {
      "size": 0,
      "timeout": 0,
      Symbol(Body internals): Object {
        "body": PassThrough {
          "_events": [Object],
          "_eventsCount": 2,
          "_maxListeners": undefined,
          "_readableState": [ReadableState],
          "_writableState": [WritableState],
          "allowHalfOpen": true,
          Symbol(kCapture): false,
          Symbol(kTransformState): [Object],
        },
        "disturbed": false,
        "error": null,
      },
      Symbol(Response internals): Object {
        "counter": 0,
        "headers": Headers {
          Symbol(map): [Object],
        },
        "status": 400,
        "statusText": "Bad Request",
        "url": "http://localhost:8889/wp-admin/admin-ajax.php?action=rest-nonce",
      },
    }

      at _getError (node_modules/jest-circus/build/utils.js:442:18)
          at Array.map (<anonymous>)

 FAIL  tests/e2e/specs/activation-flow.spec.js
  ● Activation flow › Should progress as intended

    thrown: Response {
      "size": 0,
      "timeout": 0,
      Symbol(Body internals): Object {
        "body": PassThrough {
          "_events": [Object],
          "_eventsCount": 2,
          "_maxListeners": undefined,
          "_readableState": [ReadableState],
          "_writableState": [WritableState],
          "allowHalfOpen": true,
          Symbol(kCapture): false,
          Symbol(kTransformState): [Object],
        },
        "disturbed": false,
        "error": null,
      },
      Symbol(Response internals): Object {
        "counter": 0,
        "headers": Headers {
          Symbol(map): [Object],
        },
        "status": 400,
        "statusText": "Bad Request",
        "url": "http://localhost:8889/wp-admin/admin-ajax.php?action=rest-nonce",
      },
    }

      at _getError (node_modules/jest-circus/build/utils.js:442:18)
          at Array.map (<anonymous>)
          at runMicrotasks (<anonymous>)

Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        5.958 s
Ran all test suites.
```

The key bit seems to be the `400` response from `http://localhost:8889/wp-admin/admin-ajax.php?action=rest-nonce` which doesn't seem specifically related to the tests, but perhaps to my setup?

Using `-- --puppeteer-interactive` gives the same results.

The HTTP log has the following:

```
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "GET /wp-login.php HTTP/1.1" 200 1767 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4577.0 Safari/537.36"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "HEAD / HTTP/1.1" 200 253 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "POST /wp-login.php HTTP/1.1" 302 1099 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "GET /wp-admin/admin-ajax.php?action=rest-nonce HTTP/1.1" 400 430 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "GET /index.php?rest_route=%2Fwp%2Fv2%2Fplugins&_locale=user HTTP/1.1" 403 649 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "GET /wp-admin/admin-ajax.php?action=rest-nonce HTTP/1.1" 400 430 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "POST /wp-login.php HTTP/1.1" 302 1135 "http://localhost:8889/wp-login.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4577.0 Safari/537.36"
wordpress_1  | 172.20.0.1 - - [25/Sep/2021:14:13:55 +0000] "GET /wp-admin/ HTTP/1.1" 200 15780 "http://localhost:8889/wp-login.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4577.0 Safari/537.36"
```

That is, the HeadlessChrome requests the login page (per the test), and before it can submit the login details via POST, there's a node-fetch UA that does some requests and gets 302, 403, and 400 responses.

## Expected behaviour
If it can pass on CI, I would hope it could pass locally too, without an error.

## Environment

- iTerm2 3.4.10
- Chrome 93.0.4577.63
- `@wordpress/e2e-test-utils` 5.4.3
- node v14.17.2

**Comment by pauarge** [comment]
Following the instructions, I can run the tests with no problems. I am using Node `v14.17.6` at the moment. It might be related with your setup @GaryJones, but we should definitely make the tests more resilient to different local configurations.

**Comment by GaryJones** [comment]
Since this isn't necessarily tied to the 2.6.0 milestone, I'm happy to punt this.

**Comment by GaryJones** [comment]
Closing after the method to run e2e tests was changed in #524.
